### ISSUE TITLE
Hawk

### ISSUE THREAD

**Issue by Trahaswi** [AKhilRaghav0/vf-technic#1]
Hello Hawk

**Comment by AKhilRaghav0** [comment]
> Hello Hawk

Are we about to chat? Lol use discord for that

**Comment by AKhilRaghav0** [comment]
> Hello Hawk

Are we about to chat? L

**Comment by Trahaswi** [comment]
Yes hawkeye

**Comment by Trahaswi** [comment]
> > Hello Hawk
> 
> 
> 
> Are we about to chat? Lol use discord for that

nah discord is bad for health
